# Generated by Django 4.0.5 on 2022-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('club_teams', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('nationality', models.CharField(default='', max_length=200)),
                ('awards', models.CharField(default='', max_length=200)),
                ('leagues', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
